### PR TITLE
File impl realisation

### PR DESCRIPTION
**Pull request by dianamediana**
add created repo for urls, create functions like put in Map by email, make Json file path, read urls from Json data base files, sync urls with Json data base file

### CODE REVIEW

**Review by Igor-Sergieiev-IV71 — COMMENTED** [review]
JavaDoc is absent. Functional is good. I like this commite, because I think everything works.

**Review by Igor-Sergieiev-IV71 — COMMENTED** [review]
The second commite looks pretty good, but still no documentation.

**Review by Igor-Sergieiev-IV71 — APPROVED** [review]
Final job done well.

**Review by andriyPro100 — APPROVED** [review]
It looks pretty cool. All functionality is implemented. There are not enough tests, but Igor implements them.

**Pull request merged**
